lzc-sdk-version: "0.1"
name: supabase
package: cloud.lazy.app.supabase
version: 1.25.4
description:
  开箱即用的开源后端：以 PostgreSQL 为核心，提供认证、实时、存储、自动 API 与
  Serverless，使你用最少后端工作量快速交付现代 Web/移动/AI 应用。
homepage:
  Supabase 是 Postgres 开发平台。您可以使用 Postgres 数据库、身份验证、即时
  API、边缘函数、实时订阅、存储和向量嵌入来启动您的项目。
author: supabase
application:
  subdomain: supabase
  background_task: true
  routes:
    - /=http://kong:8000/
  ingress:
    - protocol: tcp
      port: 5432
      service: supavisor
    - protocol: tcp
      port: 6543
      service: supavisor
services:
  studio:
    image: registry.lazycat.cloud/u95011260/supabase/studio:dbf8b30956d293f6
    environment:
      - HOSTNAME=0.0.0.0
      - PORT=3000
      - NEXT_PUBLIC_HOSTNAME=0.0.0.0
      - STUDIO_PG_META_URL=http://meta:8080
      - POSTGRES_PASSWORD={{ .U.POSTGRES_PASSWORD }}
      - DEFAULT_ORGANIZATION_NAME=Default Organization
      - DEFAULT_PROJECT_NAME=Default Project
      - OPENAI_API_KEY=
      - SUPABASE_URL=http://kong:8000
      - SUPABASE_PUBLIC_URL=https://${LAZYCAT_APP_DOMAIN}
      - SUPABASE_ANON_KEY={{ .U.ANON_KEY }}
      - SUPABASE_SERVICE_KEY={{ .U.SERVICE_ROLE_KEY }}
      - AUTH_JWT_SECRET={{ .U.JWT_SECRET }}
      - LOGFLARE_PRIVATE_ACCESS_TOKEN={{ .U.LOGFLARE_PRIVATE_ACCESS_TOKEN }}
      - LOGFLARE_URL=http://analytics:4000
      - NEXT_PUBLIC_ENABLE_LOGS=true
      - NEXT_ANALYTICS_BACKEND_PROVIDER=postgres
    depends_on:
      - analytics
      - meta
    health_check:
      test:
        - CMD
        - node
        - -e
        - fetch('http://studio:3000/api/platform/profile').then((r) => {if
          (r.status !== 200) throw new Error(r.status)})
  kong:
    image: registry.lazycat.cloud/u95011260/library/kong:783ea9c34b9b0f5c
    depends_on:
      - analytics
      - studio
      - auth
      - rest
      - storage
      - realtime
      - meta
    binds:
      - /lzcapp/pkg/content/api/kong.yml:/home/kong/temp.yml
    environment:
      - KONG_DATABASE=off
      - KONG_DECLARATIVE_CONFIG=/home/kong/kong.yml
      - KONG_DNS_ORDER=LAST,A,CNAME
      - KONG_PLUGINS=request-transformer,cors,key-auth,acl,basic-auth
      - KONG_NGINX_PROXY_PROXY_BUFFER_SIZE=160k
      - KONG_NGINX_PROXY_PROXY_BUFFERS=64 160k
      - SUPABASE_ANON_KEY={{ .U.ANON_KEY }}
      - SUPABASE_SERVICE_KEY={{ .U.SERVICE_ROLE_KEY }}
      - DASHBOARD_USERNAME=supabase
      - DASHBOARD_PASSWORD=this_password_is_insecure_and_should_be_updated
    entrypoint: bash -c 'sleep 10 && eval "echo \"$$(cat ~/temp.yml)\"" > ~/kong.yml && /docker-entrypoint.sh kong docker-start'

  auth:
    image: registry.lazycat.cloud/u95011260/supabase/gotrue:97e34b8931c30ba1
    environment:
      - GOTRUE_API_HOST=0.0.0.0
      - GOTRUE_API_PORT=9999
      - API_EXTERNAL_URL=https://${LAZYCAT_APP_DOMAIN}
      - GOTRUE_DB_DRIVER=postgres
      - GOTRUE_DB_DATABASE_URL=postgres://supabase_auth_admin:{{ .U.POSTGRES_PASSWORD }}@db:5432/postgres
      - GOTRUE_SITE_URL=https://${LAZYCAT_APP_DOMAIN}
      - GOTRUE_URI_ALLOW_LIST=
      - GOTRUE_DISABLE_SIGNUP=false
      - GOTRUE_JWT_ADMIN_ROLES=service_role
      - GOTRUE_JWT_AUD=authenticated
      - GOTRUE_JWT_DEFAULT_GROUP_NAME=authenticated
      - GOTRUE_JWT_EXP=3600
      - GOTRUE_JWT_SECRET={{ .U.JWT_SECRET }}
      - GOTRUE_EXTERNAL_EMAIL_ENABLED=true
      - GOTRUE_EXTERNAL_ANONYMOUS_USERS_ENABLED=false
      - GOTRUE_MAILER_AUTOCONFIRM=false
      - GOTRUE_SMTP_ADMIN_EMAIL=admin@example.com
      - GOTRUE_SMTP_HOST=supabase-mail
      - GOTRUE_SMTP_PORT=2500
      - GOTRUE_SMTP_USER=fake_mail_user
      - GOTRUE_SMTP_PASS=fake_mail_password
      - GOTRUE_SMTP_SENDER_NAME=fake_sender
      - GOTRUE_MAILER_URLPATHS_INVITE=/auth/v1/verify
      - GOTRUE_MAILER_URLPATHS_CONFIRMATION=/auth/v1/verify
      - GOTRUE_MAILER_URLPATHS_RECOVERY=/auth/v1/verify
      - GOTRUE_MAILER_URLPATHS_EMAIL_CHANGE=/auth/v1/verify
      - GOTRUE_EXTERNAL_PHONE_ENABLED=true
      - GOTRUE_SMS_AUTOCONFIRM=true
    depends_on:
      - db
      - analytics
    health_check:
      test:
        - CMD
        - wget
        - --no-verbose
        - --tries=1
        - --spider
        - http://localhost:9999/health
  rest:
    image: registry.lazycat.cloud/u95011260/postgrest/postgrest:56754e2f0bb91158
    environment:
      - PGRST_DB_URI=postgres://authenticator:{{ .U.POSTGRES_PASSWORD }}@db:5432/postgres
      - PGRST_DB_SCHEMAS=public,storage,graphql_public
      - PGRST_DB_ANON_ROLE=anon
      - PGRST_JWT_SECRET={{ .U.JWT_SECRET }}
      - PGRST_DB_USE_LEGACY_GUCS=false
      - PGRST_APP_SETTINGS_JWT_SECRET={{ .U.JWT_SECRET }}
      - PGRST_APP_SETTINGS_JWT_EXP=3600
      - PGRST_DB_CHANNEL_ENABLED=false
    command: postgrest
    depends_on:
      - db
      - analytics
  realtime:
    image: registry.lazycat.cloud/u95011260/supabase/realtime:0546ae3e8e4d3ae3
    environment:
      - PORT=4000
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=supabase_admin
      - DB_PASSWORD={{ .U.POSTGRES_PASSWORD }}
      - DB_NAME=postgres
      - DB_AFTER_CONNECT_QUERY=SET search_path TO _realtime
      - DB_ENC_KEY=supabaserealtime
      - API_JWT_SECRET={{ .U.JWT_SECRET }}
      - SECRET_KEY_BASE={{ .U.SECRET_KEY_BASE }}
      - ERL_AFLAGS=-proto_dist inet_tcp
      - DNS_NODES=''
      - RLIMIT_NOFILE=10000
      - APP_NAME=realtime
      - SEED_SELF_HOST=true
      - RUN_JANITOR=true
    depends_on:
      - db
      - analytics
    health_check:
      test:
        - CMD
        - curl
        - -sSfL
        - --head
        - -o
        - /dev/null
        - -H
        - "Authorization: Bearer {{ .U.ANON_KEY }}"
        - http://localhost:4000/api/tenants/realtime-dev/health
      timeout: 5s
      interval: 5s
      retries: 3
  storage:
    image: registry.lazycat.cloud/u95011260/supabase/storage-api:5bf488e768d809c4
    environment:
      - ANON_KEY={{ .U.ANON_KEY }}
      - SERVICE_KEY={{ .U.SERVICE_ROLE_KEY }}
      - POSTGREST_URL=http://rest:3000
      - PGRST_JWT_SECRET={{ .U.JWT_SECRET }}
      - DATABASE_URL=postgres://supabase_storage_admin:{{ .U.POSTGRES_PASSWORD }}@db:5432/postgres
      - FILE_SIZE_LIMIT=52428800
      - STORAGE_BACKEND=file
      - FILE_STORAGE_BACKEND_PATH=/var/lib/storage
      - TENANT_ID=stub
      - REGION=stub
      - GLOBAL_S3_BUCKET=stub
      - ENABLE_IMAGE_TRANSFORMATION=true
      - IMGPROXY_URL=http://imgproxy:5001
    depends_on:
      - db
      - rest
      - imgproxy
    binds:
      - /lzcapp/var/supabase-storage:/var/lib/storage
    health_check:
      test:
        - CMD
        - wget
        - --no-verbose
        - --tries=1
        - --spider
        - http://storage:5000/status
  imgproxy:
    image: registry.lazycat.cloud/u95011260/darthsim/imgproxy:0cd0d8b94d90b5ab
    environment:
      - IMGPROXY_BIND=:5001
      - IMGPROXY_LOCAL_FILESYSTEM_ROOT=/
      - IMGPROXY_USE_ETAG=true
      - IMGPROXY_ENABLE_WEBP_DETECTION=true
    binds:
      - /lzcapp/var/supabase-storage:/var/lib/storage
    health_check:
      test:
        - CMD
        - imgproxy
        - health
  meta:
    image: registry.lazycat.cloud/u95011260/supabase/postgres-meta:bc9666516cca28bf
    environment:
      - PG_META_PORT=8080
      - PG_META_DB_HOST=db
      - PG_META_DB_PORT=5432
      - PG_META_DB_NAME=postgres
      - PG_META_DB_USER=supabase_admin
      - PG_META_DB_PASSWORD={{ .U.POSTGRES_PASSWORD }}
    depends_on:
      - db
      - analytics
  functions:
    image: registry.lazycat.cloud/u95011260/supabase/edge-runtime:d511375729d5f8f8
    depends_on:
      - analytics
    binds:
      - /lzcapp/pkg/content/functions:/home/deno/functions
    environment:
      - JWT_SECRET={{ .U.JWT_SECRET }}
      - SUPABASE_URL=http://kong:8000
      - SUPABASE_ANON_KEY={{ .U.ANON_KEY }}
      - SUPABASE_SERVICE_ROLE_KEY={{ .U.SERVICE_ROLE_KEY }}
      - SUPABASE_DB_URL=postgresql://postgres:{{ .U.POSTGRES_PASSWORD }}@db:5432/postgres
      - VERIFY_JWT=false
    command: start --main-service /home/deno/functions/main
  analytics:
    image: registry.lazycat.cloud/u95011260/supabase/logflare:a227756f2691d80d
    binds:
      - /lzcapp/var/analytics:/tmp
    environment:
      - LOGFLARE_NODE_HOST=127.0.0.1
      - TMPDIR=/tmp
      - DB_USERNAME=supabase_admin
      - DB_DATABASE=_supabase
      - DB_HOSTNAME=db
      - DB_PORT=5432
      - DB_PASSWORD={{ .U.POSTGRES_PASSWORD }}
      - DB_SCHEMA=_analytics
      - LOGFLARE_PUBLIC_ACCESS_TOKEN={{ .U.LOGFLARE_PUBLIC_ACCESS_TOKEN }}
      - LOGFLARE_PRIVATE_ACCESS_TOKEN={{ .U.LOGFLARE_PRIVATE_ACCESS_TOKEN }}
      - LOGFLARE_SINGLE_TENANT=true
      - LOGFLARE_SUPABASE_MODE=true
      - LOGFLARE_MIN_CLUSTER_SIZE=1
      - POSTGRES_BACKEND_URL=postgresql://supabase_admin:{{ .U.POSTGRES_PASSWORD }}@db:5432/_supabase
      - POSTGRES_BACKEND_SCHEMA=_analytics
      - LOGFLARE_FEATURE_FLAG_OVERRIDE=multibackend=true
      - LOGFLARE_GOOGLE_CLOUD_PROJECT_ID=""
      - GOOGLE_APPLICATION_CREDENTIALS=""
      - LOGFLARE_GOOGLE_CLOUD_PROJECT_NUMBER=""
      - DATADOG_API_KEY=
      - LOGFLARE_BIGQUERY_BACKEND_ENABLED=false
      - LOGFLARE_DATADOG_BACKEND_ENABLED=false
      - LOGFLARE_POSTGRES_BACKEND_ENABLED=true
      - LOGFLARE_DISABLE_BIGQUERY=true
      - LOGFLARE_DISABLE_GOOGLE_CLOUD=true
      - LOGFLARE_BACKEND_TYPE=postgres
    depends_on:
      - db
    health_check:
      test:
        - CMD
        - curl
        - http://localhost:4000/health
      timeout: 5s
      interval: 5s
      retries: 10
  db:
    image: registry.lazycat.cloud/u95011260/supabase/postgres:3529b4327368f298
    binds:
      - /lzcapp/pkg/content/db/realtime.sql:/docker-entrypoint-initdb.d/migrations/99-realtime.sql
      # Must be superuser to create event trigger
      - /lzcapp/pkg/content/db/webhooks.sql:/docker-entrypoint-initdb.d/init-scripts/98-webhooks.sql
      # Must be superuser to alter reserved role
      - /lzcapp/pkg/content/db/roles.sql:/docker-entrypoint-initdb.d/init-scripts/99-roles.sql
      # Initialize the database settings with JWT_SECRET and JWT_EXP
      - /lzcapp/pkg/content/db/jwt.sql:/docker-entrypoint-initdb.d/init-scripts/99-jwt.sql
      # PGDATA directory is persisted between restarts
      - /lzcapp/pkg/content/db/data:/var/lib/postgresql/data
      # Changes required for internal supabase data such as _analytics
      - /lzcapp/pkg/content/db/_supabase.sql:/docker-entrypoint-initdb.d/migrations/97-_supabase.sql
      # Changes required for Analytics support
      - /lzcapp/pkg/content/db/logs.sql:/docker-entrypoint-initdb.d/migrations/99-logs.sql
      # Changes required for Pooler support
      - /lzcapp/pkg/content/db/pooler.sql:/docker-entrypoint-initdb.d/migrations/99-pooler.sql
      # Use named volume to persist pgsodium decryption key between restarts
      - /lzcapp/var/db-config:/etc/postgresql-custom
    environment:
      - POSTGRES_HOST=/var/run/postgresql
      - PGPORT=5432
      - POSTGRES_PORT=5432
      - PGPASSWORD={{ .U.POSTGRES_PASSWORD }}
      - POSTGRES_PASSWORD={{ .U.POSTGRES_PASSWORD }}
      - PGDATABASE=postgres
      - POSTGRES_DB=postgres
      - JWT_SECRET={{ .U.JWT_SECRET }}
      - JWT_EXP=3600
      - POSTGRES_LISTEN_ADDRESSES=*
    command: postgres -c log_min_messages=fatal -c listen_addresses='*' -c port=5432 -c unix_socket_directories='/var/run/postgresql' -c shared_preload_libraries='pg_net,pg_stat_statements' -c wal_level=logical
    health_check:
      test:
        - CMD
        - pg_isready
        - -U
        - postgres
        - -h
        - localhost
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 60s
  vector:
    image: registry.lazycat.cloud/u95011260/timberio/vector:68c5884c3e523f6f
    binds:
      - /lzcapp/pkg/content/logs/vector.yml:/etc/vector/vector.yml
    environment:
      - LOGFLARE_PUBLIC_ACCESS_TOKEN={{ .U.LOGFLARE_PUBLIC_ACCESS_TOKEN }}
    depends_on:
      - analytics
      - rest
      - realtime
      - auth
      - storage
      - kong
    command: --config /etc/vector/vector.yml
    health_check:
      test:
        - CMD
        - wget
        - --no-verbose
        - --tries=1
        - --spider
        - http://vector:9001/health
      timeout: 5s
      interval: 10s
      retries: 5
      start_period: 30s
  supavisor:
    image: registry.lazycat.cloud/u95011260/supabase/supavisor:24de9bc097db8336
    depends_on:
      - db
      - analytics
    binds:
      - /lzcapp/pkg/content/pooler/pooler.exs:/etc/pooler/pooler.exs
    environment:
      - PORT=4000
      - POSTGRES_PORT=5432
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD={{ .U.POSTGRES_PASSWORD }}
      - DATABASE_URL=ecto://supabase_admin:{{ .U.POSTGRES_PASSWORD }}@db:5432/_supabase
      - CLUSTER_POSTGRES=true
      - SECRET_KEY_BASE={{ .U.SECRET_KEY_BASE }}
      - VAULT_ENC_KEY={{ .U.VAULT_ENC_KEY }}
      - API_JWT_SECRET={{ .U.JWT_SECRET }}
      - METRICS_JWT_SECRET={{ .U.JWT_SECRET }}
      - REGION=local
      - ERL_AFLAGS=-proto_dist inet_tcp
      - POOLER_TENANT_ID=supabase-project
      - POOLER_DEFAULT_POOL_SIZE=20
      - POOLER_MAX_CLIENT_CONN=100
      - POOLER_POOL_MODE=transaction
      - DB_POOL_SIZE=5
      - POSTGRES_HOST=db
    command: /bin/sh -c "/app/bin/migrate && /app/bin/supavisor eval \"$$(cat /etc/pooler/pooler.exs)\" && /app/bin/server"
