# 全局参数
uid = root
gid = root
use chroot = no
max connections = 4
timeout = 300
pid file = /var/run/rsyncd.pid
lock file = /var/run/rsync.lock

# 实时输出设置
log file = /dev/stdout
transfer logging = yes
log format = %t rsync [%p] %o %h [%a] %m %f %l

[lzcapp]
path = /lzcapp
read only = no
dont compress = *.gz *.bz2 *.zip

[root]
path = /root/
read only = no
dont compress = *.gz *.bz2 *.zip

[tmp]
path = /tmp/
read only = no
dont compress = *.gz *.bz2 *.zip